// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $buttons_SettingButton from "./islands/buttons/SettingButton.tsx";
import * as $buttons_SwitchDarkModes from "./islands/buttons/SwitchDarkModes.tsx";
import * as $edit from "./islands/edit.tsx";
import * as $editor from "./islands/editor.tsx";
import * as $init from "./islands/init.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/buttons/SettingButton.tsx": $buttons_SettingButton,
    "./islands/buttons/SwitchDarkModes.tsx": $buttons_SwitchDarkModes,
    "./islands/edit.tsx": $edit,
    "./islands/editor.tsx": $editor,
    "./islands/init.tsx": $init,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
